.\" Nodelint [VERSION]
.\" [DATE]
.\" A fork of tav's nodelint (http://github.com/tav/nodelint)
.\" Corey Hart @ http://www.codenothing.com
.
.TH "#{display}" "1" "[DATE]"
.
.SH "NAME"
#{name} \- #{display} with Node\.
.
.SH "SYNOPSIS"
\fB#{name}\fR [options] file\.js [file2\.js dir dir2]
.
.SH "DESCRIPTION"
\fB#{name}\fR is a command line tool that runs designated files through the #{display} parser to check for syntax errors\.
.
.SH "Options"
.
.SS "\-l \fIFILE\fB, \-\-logfile=\fIFILE\fR"
Define a logfile to output results to\.
.
.SS "\-e \fIENCODINGS\fB, \-\-encodings=\fIENCODINGS\fR"
Define a comma-sparated list of encodings to check for\.
.
.SS "\-c, \-\-no-color"
Disable coloring of output\.
.
.SS "\-v, \-\-verbose"
Verbose mode\. Outputs processing information like what directory is currently being read, or what file is currently being linted\.
.
.SS "\-p, \-\-show\-passed"
Output list of files that passed #{name}\.
.
.SS "\-i, \-\-show\-ignored"
Output list of files ignored based on lintignore files\.
.
.SS "\-m, \-\-show\-missing"
Output missing files that were expected\.
.
.SS "\-w, \-\-show\-warnings"
Output warning messages during processing\.
.
.SS "\-\-#{name}=\fIFILE\fR"
Define a custom #{name} file to use\.
.
.SH "Using #{display} Options"
#{name} --#{name}_option=value [more options] file.js
