.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "JSLINT" "1" "[DATE]" "" ""
.
.SH "NAME"
\fBjslint\fR \-\- JSLint with Node\. jslint is a an extension of Nodelint\.
.
.SH "Usage"
jslint [options] file\.js [file2\.js dir dir2]
.
.SH "Options"
.
.SS "\-l \fIFILE\fR, \fB\-\-logfile\fR=\fIFILE\fR"
Define a logfile to output results to\.
.
.SS "\-j \fIFILE\fR, \fB\-\-jslint\fR=\fIFILE\fR"
Define a custom jslint file to use\.
.
.SS "\-b \fITIME\fR, \fB\-\-buffer\-wait\fR=\fITIME\fR"
Define the number of milliseconds(TIME) to wait for buffer output to finish before killing the process\. Usefull for pre\-commit hooks
.
.SS "\-i, \-\-show\-ignored"
Output list of files ignored based on lintignore files\.
.
.SS "\-m, \-\-show\-missing"
Output missing files that were expected\.
.
.SS "\-w, \-\-show\-warnings"
Output warning messages during processing\.
