.\" Nodelint [VERSION]
.\" [DATE]
.\" A fork of tav's nodelint (http://github.com/tav/nodelint)
.\" Corey Hart @ http://www.codenothing.com
.
.TH "NODELINT-BASE" "1" "[DATE]"
.
.SH "NAME"
Nodelint \- Project linting with Node\.
.
.SH "SYNOPSIS"
\fBnodelint-base\fR [options] file\.js [file2\.js dir dir2]
.
.SH "DESCRIPTION"
\fBnodelint-base\fR is the non-cli form of nodelint, a tool that runs designated files through various parsers to check for syntax errors\.
It can be used on the command line, as a pre\-commit hook, or incorporated into your build process\.
.
.SH "Options"
.
.SS "\-l \fIFILE\fB, \-\-logfile=\fIFILE\fR"
Define a logfile to output results to\.
.
.SS "\-e \fIENCODINGS\fB, \-\-encodings=\fIENCODINGS\fR"
Define a comma-sparated list of encodings to check for\.
.
.SS "\-c, \-\-no-color"
Disable coloring of output\.
.
.SS "\-v, \-\-verbose"
Verbose mode\. Outputs processing information like what directory is currently being read, or what file is currently being linted\.
.
.SS "\-p, \-\-show\-passed"
Output list of files that passed their linters\.
.
.SS "\-i, \-\-show\-ignored"
Output list of files ignored based on lintignore files\.
.
.SS "\-m, \-\-show\-missing"
Output missing files that were expected\.
.
.SS "\-w, \-\-show\-warnings"
Output warning messages during processing\.
.
.SS "\-\-Nodelint\-cli"
Trigger Cli run of arguments\.
.
.SS "\-\-Nodelint\-pre\-commit=\fIVCS\fR"
Run the pre\-commit hook on files to be committed for the version control system defined\. Blocks commit on error\.
.
.SS "\-\-Nodelint\-pre\-commit\-all"
Run Nodelint across the entire project before, and block commit on error\.
