.\" Nodelint [VERSION]
.\" [DATE]
.\" A fork of tav's nodelint (http://github.com/tav/nodelint)
.\" Corey Hart @ http://www.codenothing.com
.
.TH "NODELINT" "1" "[DATE]"
.
.SH "NAME"
nodelint \- Project linting with Node\.
.
.SH "SYNOPSIS"
\fBnodelint\fR [options] file\.js [file2\.js dir dir2]
.
.SH "DESCRIPTION"
\fBnodelint\fR is a command line tool that runs designated files through multiple parsers to check for syntax errors\.
.
.SH "Options"
.
.SS "\-l \fIFILE\fB, \-\-logfile=\fIFILE\fR"
Define a logfile to output results to\.
.
.SS "\-e \fIENCODINGS\fB, \-\-encodings=\fIENCODINGS\fR"
Define a comma-sparated list of encodings to check for\.
.
.SS "\-v, \-\-verbose"
Verbose mode\. Outputs processing information like what directory is currently being read, or what file is currently being linted\.
.
.SS "\-p, \-\-show\-passed"
Output list of files that passed their linters\.
.
.SS "\-i, \-\-show\-ignored"
Output list of files ignored based on lintignore files\.
.
.SS "\-m, \-\-show\-missing"
Output missing files that were expected\.
.
.SS "\-w, \-\-show\-warnings"
Output warning messages during processing\.
