.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "NODELINT" "1" "[DATE]" "" ""
.
.SH "NAME"
\fBNodelint\fR \-\- JSLint with Node\. Nodelint is a tool that runs designated files through the JSLint parser to check for
syntax errors\. It can be used on the command line, as a pre\-commit hook, or incorporated
into your build process\.
.
.SH "Usage"
Nodelint [options] file\.js [file2\.js dir dir2]
.
.SH "Options"
.
.SS "\-l \fIFILE\fR, \fB\-\-logfile\fR=\fIFILE\fR"
Define a logfile to output results to\.
.
.SS "\-j \fIFILE\fR, \fB\-\-jslint\fR=\fIFILE\fR"
Define a custom jslint file to use\.
.
.SS "\-b \fITIME\fR, \fB\-\-buffer\-wait\fR=\fITIME\fR"
Define the number of milliseconds(TIME) to wait for buffer output to finish before killing the process\. Usefull for pre\-commit hooks
.
.SS "\-v, \-\-verbose"
Verbose mode\. Outputs processing information like what directory is currently being read, or what file is currently being linted\.
.
.SS "\-p, \-\-show\-passed"
Output list of files that passed jslint\.
.
.SS "\-i, \-\-show\-ignored"
Output list of files ignored based on lintignore files\.
.
.SS "\-m, \-\-show\-missing"
Output missing files that were expected\.
.
.SS "\-w, \-\-show\-warnings"
Output warning messages during processing\.
.
.SS "\-\-Nodelint\-Cli"
Trigger Cli run of arguments\.
.
.SS "\-\-Nodelint\-pre\-commit=\fIVCS\fR"
Run the pre\-commit hook on files to be commited for the version control system defined\. Blocks commit on error\.
.
.SS "\-\-Nodelint\-pre\-commit\-all"
Run Nodelint across the entire project before, and block commit on error\.
