#! /usr/bin/env node
/* vim:set ft=javascript : */
/*
 * Nodelint [VERSION]
 * [DATE]
 * A fork of tav's nodelint (http://github.com/tav/nodelint)
 * Corey Hart @ http://www.codenothing.com
 */

// Turn on simple verbose 
var Nodelint = require('Nodelint');
Nodelint.Options.nodelint.verbose = true;
Nodelint.Options.nodelint[ 'show-passed' ] = true;

// caling jslint directly, so no 'node nodelint.js'
Nodelint.cli( 1 );
